# Site settings
title:          Soham Bakshi
description:    "Statistical Analyst and Researcher"
baseurl:        "/BakSo"
url:            "https://arkopaldas.github.io"

paginate:       5

# Build settings
markdown:       kramdown
highlighter:         rouge
permalink:      /:year-:month-:day/:title

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Author
author:
  name:         Soham Bakshi
  url:          https://arkopaldas.github.io/BakSo
  email:        bakso@umich.edu
