# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-1'

menu:
- {name: 'Home', url: 'index.html'}
- {name: 'Research', url: 'research.html'}
# - {name: 'About',    url: 'about.html'}
- {name: 'Teaching', url: 'teaching.html'}
- {name: 'হ য ব র ল',  url: 'writing.html'}
# - {name: 'Contact',  url: 'contact.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'file-pdf', link: 'assets/file/cv.pdf'}
- {icon: 'github', link: 'https://github.com/BakshiSoham'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=WuIfUrYAAAAJ&hl=en'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/soham-bakshi-186b56180'}
- {icon: 'envelope', link: 'mailto:bakso@umich.edu'}
- {icon: 'instagram', link: 'https://www.instagram.com/meaningfully_meaningless/'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy:'

# post_date_prefix: 'Written on'
